name: 'Authenticate with FTL (TypeScript)'
description: 'Explicit OAuth authentication for FTL platform access'
author: 'TBD'

branding:
  icon: 'key'
  color: 'orange'

inputs:
  method:
    description: 'Authentication method: auto, interactive'
    required: false
    default: 'auto'
  client-id:
    description: 'OAuth client ID'
    required: false
  client-secret:
    description: 'OAuth client secret'
    required: false
  set-output:
    description: 'Set token as action output (use with caution)'
    required: false
    default: 'false'

outputs:
  token:
    description: 'OAuth access token (only if set-output=true)'

runs:
  using: 'node20'
  main: 'dist/index.js'