name: FTL Test

on:
  push:
    branches: [ feat/github-actions-modernization ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ftl-test:
    name: FTL Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup FTL CLI with Dependencies
        uses: ./actions/setup-ftl-js
        with:
          version: 'latest'
          use-cache: true