name: 'FTL Engineering Deploy (TypeScript)'
description: 'Deploy FTL applications to engineering platform with OAuth authentication'
author: 'TBD'

branding:
  icon: 'upload-cloud'
  color: 'purple'

inputs:
  project:
    description: 'Project name to deploy'
    required: true
  environment:
    description: 'Target environment'
    required: false
    default: 'staging'
  client-id:
    description: 'OAuth client ID (or use authenticate-ftl action)'
    required: false
  client-secret:
    description: 'OAuth client secret (or use authenticate-ftl action)'
    required: false
  wait-for-completion:
    description: 'Wait for deployment to complete'
    required: false
    default: 'true'

outputs:
  deployment-id:
    description: 'Unique deployment identifier'
  deployment-url:
    description: 'URL to view deployment status'
  status:
    description: 'Deployment status'

runs:
  using: 'node20'
  main: 'dist/index.js'